name: CI

# Trigger on pushes and pull requests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run Cargo Tests
    runs-on: ubuntu-latest

    steps:
      # Check out the repo.
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Rust toolchain.
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Lint
        run: cargo clippy --all --all-targets -- -D warnings

      - name: Check
        run: cargo check --all

      - name: Run tests
        run: cargo test --all
